### ISSUE TITLE
玩家救援MOD

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#10]
叫玩家救援 效果是它允许玩家在死亡后60秒内被救起。
介绍https://www.mcmod.cn/class/1914.html
下载链接https://winn.lanzoum.com/iCZSW0mkq8re

**Comment by Moon-404** [comment]
看上去你似乎无法处决一个濒死的人，但这问题不大。问题是我似乎没有看到可以令玩家立即死亡的指令，如果队伍玩家全部死亡，游戏逻辑可能无法正确判断。
