### ISSUE TITLE
免除干草块摔落伤害的MOD

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#11]
在干草块上面摔落将不会受到伤害
介绍https://www.mcmod.cn/class/4309.html
下载https://www.curseforge.com/minecraft/mc-mods/softer-hay-bales

**Comment by Moon-404** [comment]
摔落伤害是限制玩家无脑上高点的手段，除非整体战斗机制大改，否则不会进行改动。

**Comment by BallyJery** [comment]
实际上可以通过使用肾上腺素受伤的无敌帧免除掉落伤害?

**Comment by Moon-404** [comment]
这种需要一定操作实现的技巧在设计时应当默认玩家不会使用。
