### ISSUE TITLE
[疑问]关于切枪公平性问题

### ISSUE THREAD

**Issue by BeiGuaOvO** [Moon-404/GunBattleRoyale#12]
材料：
https://user-images.githubusercontent.com/118031352/216819398-211b16a0-849d-4f9c-99d9-151b3f5786e3.mp4

争议：
秒切只会卡掉冷却显示不会卡掉武器攻击CD ——琉璃
这个问题能否给出具体的解答 或者说ban的原因

**Comment by Moon-404** [comment]
使用一把武器攻击后使用另一把武器补枪是正常操作，这无问题。有问题和禁用的是在冷却时间结束前再次开火的BUG行为，这个行为会被服务器记录在后台。诚然，这也有可能是网络延迟或者服务器卡顿导致的，但是如果一名玩家触发这个的次数明显较高，那说明该玩家在刻意利用该特性。
