### ISSUE TITLE
模组建议——跑酷

### ISSUE THREAD

**Issue by yuhangming44** [Moon-404/GunBattleRoyale#14]
服主你好，服务器能不能加一个parcool(跑酷)模组，我自己认为原版动作稍少，如果加上这个模组可以有更多躲枪、身法技巧

**Comment by Moon-404** [comment]
暂时不考虑，跑酷模组与现有模组的兼容性需要大量的测试与调整，这不在目前的规划中。

**Comment by yuhangming44** [comment]
好的，我也明白这需要大量的时间，不加入也没有关系，希望服务器越做越好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moon-404/GunBattleRoyale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月11日(星期六) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moon-404/GunBattleRoyale] 模组建议——跑酷 (Issue #14)





 
暂时不考虑，跑酷模组与现有模组的兼容性需要大量的测试与调整，这不在目前的规划中。
