### ISSUE TITLE
about using Bukkit Server and some anticheat idea

### ISSUE THREAD

**Issue by nyakochanNeee** [Moon-404/GunBattleRoyale#15]
**All things not tested just a idea** 

> https://www.fastmirror.net/#/download/Arclight 一个兼容核心 不知道是否适用
>https://www.spigotmc.org/resources/soaromasac-lightweight-cheat-detection-system-for-java-bedrock.87702 一个反作弊 适用于生存 很少检测PVP 主要检测移动 没找到src qwq 或者可以去看看NCP
>catanticheat的src https://github.com/Luohuayu/CatAntiCheat-Public/ 我没有时间去学习java 我本身是看不懂的QWQ

_还有一点IDEA 插件可以加点反压测的登陆什么的_

**Comment by Moon-404** [comment]
由于我现在不会把主要精力放在这个模组的开发和维护上，我不会花时间去测试它们是否会有兼容问题（Arclight 似乎有一些兼容问题）如果您愿意，您可以在详细测试后再继续向我建议。

**Comment by nyakochanNeee** [comment]
**tested**

> **Mohist**  https://www.fastmirror.net/#/download/Mohist?coreVersion=1.19.2
> ~~**authme(登陆插件)** https://github.com/AuthMe/AuthMeReloaded/releases~~ (cant use)
> **LuckPerms(权限组插件)** https://luckperms.net (Bukkit)
> **Skript(脚本插件)**  https://github.com/SkriptLang/Skript
> **MV多世界插件** https://www.spigotmc.org/resources/multiverse-core.390/

> **Using JAVA17**

**Comment by nyakochanNeee** [comment]
Running Screenshot
![image](https://user-images.githubusercontent.com/100355329/218447097-b88c3952-7566-41b6-9931-7e5ee3636530.png)
mods
![image](https://user-images.githubusercontent.com/100355329/218447172-adf4799b-63e0-40dc-8ed0-66bc21ea25da.png)

忘记测试的插件
[NoChatReports.-.1.1.0.jar.zip](https://github.com/Moon-404/GunBattleRoyale/files/10721757/NoChatReports.-.1.1.0.jar.zip)

**Comment by Moon-404** [comment]
我会近期在测试服测试 Mohist 这个端，感谢反馈。如果这个端没有问题，未来会考虑加入一些别的插件以维护服务器的稳定。

**Comment by Moon-404** [comment]
服务端启动时出现了 `java.lang.OutOfMemoryError` 错误，该端对内存的要求似乎比 Forge 端要大，服务端无法正常启动。

**Comment by Moon-404** [comment]
经过测试，是因为 Mohist 启动原版端时会屏蔽启动时的 Xmx 参数，导致原版端以默认的内存（物理内存的四分之一）启动。解决方法是使用 `export _JAVA_OPTIONS="-Xmx1500M"` 设置默认的启动内存。

**Comment by Moon-404** [comment]
经过测试，Mohist 端会有包括无法选队在内的许多问题，而原版 Forge 端并没有，服务器不会使用这个端。
