### ISSUE TITLE
[Sever bug] 战利品刷新问题

### ISSUE THREAD

**Issue by BeiGuaOvO** [Moon-404/GunBattleRoyale#16]
材料：
![R4Y`W9_1NZ~DJ(VY _R`Z@U](https://user-images.githubusercontent.com/118031352/221187945-13060fea-01ad-4acd-834b-73060cdbb2ee.png)
![%L5DRTU3%1PR8BNO%0ICW83](https://user-images.githubusercontent.com/118031352/221187971-a0976c23-468b-46d1-8a3b-77aed29eba30.png)
具体详见q群

**Comment by Moon-404** [comment]
系地图制作者未放置 supply 标记盔甲架导致
