### ISSUE TITLE
关于跳伞塔和摔落伤害

### ISSUE THREAD

**Issue by imagineerrox** [Moon-404/GunBattleRoyale#17]
我想在新地图中添加跳伞塔，摔落伤害可以做到单独玩家单独免疫吗。因为目前实现最好的办法是水电梯/漂浮buff和鞘翅，但是服务器鞘翅会在一定距方块高度收回并且服务器并没有摔落伤害免疫，如何让跳伞玩家规避落地伤害又i防止该玩家利用规避效果攻击其他玩家，这是个亟待解决的问题。我目前没有更好的办法去实现跳伞塔。

**Comment by Moon-404** [comment]
这个问题困扰了我很久，昨天有人提出可以用缓降效果来代替跳伞末尾的无敌效果，我会在下个版本测试这个修改的可行性

**Comment by Moon-404** [comment]
下个版本会用3秒缓降代替现在的落地无敌，具体效果待测试
