### ISSUE TITLE
关于武器开火间隔和切枪速度

### ISSUE THREAD

**Issue by imagineerrox** [Moon-404/GunBattleRoyale#18]
现在近距离作战都是霰弹枪和步枪命中瞬间拉开血量差距再秒切冲锋枪收割。这种行为极大缩短了游戏的ttk，并且影响游玩体验，虽然后台能检测这样的异常行为，但是无人举报。因此根治这样的操作需要其他方式。我目前的想法是增加切换武器到开枪的最短时间，即切枪时间（或者可以理解成预热时间），但我目前还没更好的想法如何实现。

另外关于武器的携带数量，我认为在以后的版本也应该进行限制。

**Comment by Moon-404** [comment]
使用单发武器打出血量优势后使用自动武器补伤害是正确的打法，APEX 和我的视频里也有类似的操作。问题在于连续切出多把高伤害的单发武器会在极短时间内造成不合理的伤害。切枪时间是应当加上的，我目前有几种设想：

1. 武器开火后，背包中的所有武器都会进入冷却，冷却时间与开火间隔相同
2. 切换到一把武器后，会有短暂的冷却时间（这个冷却时间如何设定需要再做思考）

具体如何操作还需要进行思考和测试，感谢反馈。

**Comment by Moon-404** [comment]
下个版本会使用设想 1 进行测试与修改
