### ISSUE TITLE
关于[移动模式的创新]问题

### ISSUE THREAD

**Issue by lkctrl** [Moon-404/GunBattleRoyale#19]
对于现在移动模式我觉得有一点点单一：也就跑和蹲（蹲也没多大用）。
我建议可以增加一些新的移动模式：比如蹲伏、卧倒、滑铲等。
这些对于目前来说可以开发出来更多的打法以及战术，可以在一定程度上增加对枪时候的灵敏性。

**Comment by Moon-404** [comment]
原版MC的潜行可以降低玩家的受击体积来更好地躲在掩体后，此外还可以避免玩家失足掉落，并非没多大用。

新的移动模式首先需要有键位的支持，此外还要符合MC的游戏习惯。

蹲伏和潜行区别不大，卧倒在拥有位移和扫描技能的本MOD中优势不明显，滑铲可能是最有用的一个移动模式，我会进行尝试，但制作有一定难度。

**Comment by link-fgfgui** [comment]
[跑酷](https://www.mcmod.cn/class/5958.html) Mod有很丰富的动作
![image](https://user-images.githubusercontent.com/96362154/229271530-81e970f8-a24f-4839-b064-419cc063e891.png)
![image](https://user-images.githubusercontent.com/96362154/229271536-10e227c3-6d90-423f-945d-0d4d05fd97df.png)

**Comment by Moon-404** [comment]
该模组的动作远超本模组的使用需求，故不会直接用。下个版本会加入滑铲与攀爬机制，也有参考这个模组的源码。
