### ISSUE TITLE
关于新的护甲机制

### ISSUE THREAD

**Issue by imagineerrox** [Moon-404/GunBattleRoyale#21]
由于新的护甲机制的出现，极大程度的降低了游戏的ttk，实战对局中“金甲”非常难进化到。大多数情况是紫甲或者蓝甲的战斗，而最高等级的金甲只是对应了之前版本的满血。因此我认为护甲基础血量即白甲可以变为1管五颗心即30血，蓝甲一管7.5颗心即35血，紫甲两管即40血，金甲两管两颗半即45血，此外护盾进化材料及其珍贵且稀有，我建议加入空投之中，以降低升级护甲的门槛。

**Comment by imagineerrox** [comment]
哦对了伤害数字如果能有白色发光边框或许会更好，更醒目显眼。

**Comment by Moon-404** [comment]
针对这个问题，降低了每一次进化需要的伤害和枪械的DPS，感谢反馈。

伤害数字渲染问题我之后再研究，目前重点不在这里。
