### ISSUE TITLE
快捷轮盘使用的建议

### ISSUE THREAD

**Issue by zongmingzhu233** [Moon-404/GunBattleRoyale#22]
今天测试的快捷轮盘使用
建议是如果空手选择快捷轮盘所在的按键(默认第四第五格)，仍然可以将背包里面所拥有的物品（医疗品或者技能）拿取到快捷栏中

**Comment by Moon-404** [comment]
轮盘会把背包中的相应物品替换到快捷栏中，无论手上是否持有物品。你这个建议目前就已经是这样了。

**Comment by zongmingzhu233** [comment]
好的，但是今天晚上的对局中我并不能这样做，请问这个是否为bug？？？
