### ISSUE TITLE
关于管理员可以随意骂人几页 我却不能阴阳一句这件事

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#25]
![image](https://user-images.githubusercontent.com/89908099/227663252-0783faec-a32c-446d-afe9-7f8b0d58ea45.png)
太酷了 原来管理员可以这样随便神权的吗

**Comment by BallyJery** [comment]
就算我违反了规则 不也要根据公告进行举报？
管理员高人一等是吧

**Comment by Moon-404** [comment]
首先，公告中的举报机制是针对服务器管理设立的，对群内环境的维护并不以此公告为依据。附：公告原文。

![image](https://user-images.githubusercontent.com/33384538/227667323-99d23e3a-71eb-4507-baae-b6f6e45f1ccd.png)

其次，这是您被移除前的发言，这段发言具有明显的阴阳怪气与人身攻击倾向，管理员为了维护群内环境采取措施并无不妥。

![image](https://user-images.githubusercontent.com/33384538/227667465-4beb5ebc-fdab-4241-abff-e960e7d6d7e2.png)

最后是我个人的一点建议：察言观色是在社会上行走的必备能力，火上浇油逞一时之快可能会给自己带来不必要的麻烦。

**Comment by BallyJery** [comment]
你要不往上看看管理员的发言？就是说管理员可以随意禁言踢出？

**Comment by BallyJery** [comment]
管理员攻击性高阴阳我的时候也没见我可以踢出人啊

**Comment by BallyJery** [comment]
我阴阳怪气 × 
管理员神权骂人 √

**Comment by BeiGuaOvO** [comment]
iussues不是这么用的
哥们
