### ISSUE TITLE
充能步枪太过超模

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#26]
机枪刮痧+高扩散
大狙就是步枪多点伤害
而我们的充能步枪呢 
不但粘人 伤害还高 射速还快
守点无脑滋滋滋
冲锋直接提前枪
可远可近
被打到了基本就得吃后面几枪
类比其他空投武器
感觉太超模了

**Comment by Moon-404** [comment]
你说得对，我也已经注意到了这个问题，所以在 v33 版本的改动中，我更改了很多枪械的数据，也重新规划了地面战利品与空投枪械种类，希望能改善这个问题。
