### ISSUE TITLE
[建议]关于新武器——霰弹枪的一些问题

### ISSUE THREAD

**Issue by BeiGuaOvO** [Moon-404/GunBattleRoyale#4]
问题：现测试服霰弹枪伤害、备蛋过于离谱，贴脸一枪40血（直接死），5-8格30血（剩5颗心），并且不在空投箱武器池里，现给出一些建议：
1.将霰弹枪弹匣容量换为2
2.将伤害适量下调
3.（将此武器放置在空投武器池里）
以上建议可以任选实现
（tips：只是建议，不代表一定要实现）

**Comment by Moon-404** [comment]
收到
