### ISSUE TITLE
关于车队三打一

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#6]
个人认为车队包人有点无解

**Comment by bailijerry** [comment]
提出几种建议：

**Comment by BallyJery** [comment]
提出一点建议
1、提高最大血量 让其不容易被秒
2、加入防御道具 比如（地雷、失明陷阱等）
3、限制组队 前3或前5 不能在同一个队伍
4、反扫描的道具（设置为比较稀有但是获取难度不大）

**Comment by Moon-404** [comment]
关于您的“车队包人有点无解”，配合良好的玩家比没有配合的玩家更有竞争力是很正常的，尤其是在这种大逃杀的游戏机制下。至于您的建议，我一一回复：

1. 生命值不会更改，这个调整需要牵扯到非常多的数值调整。
2. 防御道具暂时不会加入，这会让抱团防守更加难以突破。
3. 限制组队对水平较高的玩家反而不公平。
4. 反扫描的道具暂时不会加入，不过这是个很有意思的想法。

值得一提的是，本MOD完全开源，您可以自己fork一份进行修改。我也支持您将修改的内容使用pull request的方式提交给我，我会很乐意将其更新入MOD。对于您的烦恼，我有以下建议：

1. 寻找一起游玩的朋友，享受团队合作的乐趣。
2. 跳伞时与队友一起行动，降低被抓单的概率。
3. 当发现自己被扫描出来的时候，关注其它玩家的位置，尤其是对自己威胁较大的多人小队，提前规避。
4. 一对多战斗时尽量创造单挑的机会，虽然有经验的玩家会避免这种情况。
5. 利用“单排与三排不能混排”的规则，当您认为已有的三人小队威胁过大时，使用这种方式来制止。发生这种僵持情况时，我倾向于三人小队分出人到单人小队中以开始游戏。

感谢您的建议，也希望我的回复可以让您体会到模组的乐趣。
