### ISSUE TITLE
关于测试服

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#7]
找到两个mod 能解决测试服的登录和皮肤的问题

**Comment by BallyJery** [comment]
自定义皮肤：https://winn.lanzoum.com/i2Pgo0miwdyf
登录mod:https://winn.lanzoum.com/iFqZZ0miwe2j

**Comment by Moon-404** [comment]
测试服是用来测试的，因为需要经常重启且不保留数据，所以不会花过多精力在上面
