### ISSUE TITLE
Mod建议——PING

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#8]
找到一个叫Ping的mod
它的功能是按V标记一个地方 比如goto 或者look
个人感觉比打字交流方便 
下载链接：https://winn.lanzoum.com/isJmP0miz0ja

**Comment by BallyJery** [comment]
Mod介绍 https://www.mcmod.cn/class/1740.html

**Comment by Moon-404** [comment]
这个MOD看起来很不错，我会考虑将其安装至服务器

**Comment by BallyJery** [comment]
有个问题是他好像并不是兼容队伍
明天我看看能不能设置范围或者能看到的玩家
默认设置是同一纬度都能看到标记

**Comment by Moon-404** [comment]
我测试了一下，发现这个PING出来的信号无论队伍都可以被接收，且标记有距离限制，不适合这个MOD。
