### ISSUE TITLE
Mod建议——遗体

### ISSUE THREAD

**Issue by bailijerry** [Moon-404/GunBattleRoyale#9]
找到一个叫遗体的mod
功能是在没有开启死亡不掉落的情况下，玩家的物品会存储在遗体里，玩家可以右键遗体并拿回自己的物品
感觉装上会比原来掉落物散落在一大圈好
可以游戏后通过/kill @e[type=corpse:corpse] 清除遗体
Mod介绍https://www.mcmod.cn/class/3007.html
下载链接https://winn.lanzoum.com/iCZSW0mkq8re

**Comment by Moon-404** [comment]
可以拿别人的物品吗？

**Comment by BallyJery** [comment]
好像是任何人都能拿

**Comment by Moon-404** [comment]
好的，我需要再考虑一下是否将这个模组纳入前置。

**Comment by bailijerry** [comment]
这个Mod在Config文件夹内的配置文件可以能设置标记的范围和看得见标记的范围 
![image](https://user-images.githubusercontent.com/89908099/216741015-1bb44942-cb7b-434a-8a25-21c7f3c669b4.png)

**Comment by Moon-404** [comment]
这个范围与队伍无关，且不要再无关Issue回复。在提Issue时就应当把这些内容都考虑到，这才是合格的建议。
